### PR TITLE
Resolves issue #25

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Resolves issue #25.

### CODE REVIEW

**Comment by peter279k** [comment]
The expected Travis CI build is failed because the coding style check is failed without fix.

**Comment by peter279k** [comment]
And I also found other problems:

The fatal error message is as follows:

```
In ConfigurationResolver.php line 758:
                                                                               
  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]       
  The rules contain unknown fixers: "declare_strict_types " (did you mean "de  
  clare_strict_types"?), "lowercase_static_reference " (did you mean "lowerca  
  se_static_reference"?), "phpdoc_order " (did you mean "phpdoc_order"?).  
```

Is the `PHP-CS-Fixer` configuration file correct?

I think the configuration value settings are incorrect.

**Comment by peter279k** [comment]
Ok. I found where the problem is.

And I also submit the [PR](https://github.com/phootwork/php-cs-fixer-config/pull/2) about fixing `PHP-CS-Fixer` config values.

Once that PR is merged, this Travis CI build will be successful, too.

**Comment by cristianoc72** [comment]
Ok,I merged you're PR https://github.com/phootwork/php-cs-fixer-config/pull/2 and drafted a new release. Now `composer cs`works correctly.
The Travis build fails because the coding standard is not still fixed.
This PR is ready to merge for me.

**Review by gossi — APPROVED** [review]

**Comment by gossi** [comment]
Looks good. Thanks @cristianoc72 for fixing the related bug right away. Gonna merge this. @peter279k can you provide a follow-up PR to fix cs?

**Comment by peter279k** [comment]
Hi @gossi. Sure. I will create another PR about following up the `cs-fix`.

**Pull request merged**
