### PR TITLE
Fix issue 21

### LINKED ISSUE #21: [text] Unused methods
It seems that the following two methods are never used:
https://github.com/phootwork/phootwork/blob/1f3396e5073d4823630b2a547619aacd53ea6583/src/lang/Text.php#L1105
https://github.com/phootwork/phootwork/blob/1f3396e5073d4823630b2a547619aacd53ea6583/src/lang/Text.php#L1080

Could we remove them?

### PR DESCRIPTION
**Pull request by cristianoc72**
Fix #21 and split the Text class into several parts. This fix some Codeclimate/Scrutinizer issues and improve code quality.

### CODE REVIEW

**Review by peter279k — APPROVED** [review]
That's right.

I think it's fine to separate these traits and classes to one trait and class.

Every trait and class file should be separated.

**Comment by gossi** [comment]
I see, it makes cc/scrutinizer happy. I'm wondering of how much of these traits are reusable? Consider them as _public_ API. Can I from my library use such traits and gain any benefits? If we also get _that_ use-case done properly, that would be awesome.

**Comment by cristianoc72** [comment]
@gossi to be honest, the true PR is removing two unused methods. I also tried to split Text class into smaller pieces to see the reaction of our "smart tools" and to know your thought about it.
Code climate is super enthusiast and it rates our library *A* instead of C :smile: but I can't see a real need of this refactor and I can't see an use-case where I can re-use one of those traits.

**Review by gossi — APPROVED** [review]

**Comment by gossi** [comment]
Haha, yes. I think some of those traits have the potential of being used outside of phootwork's internals. For example, somebody might want to use the `SearchPart` or `TransformationPart` on their classes. If we turn `$this->string` to `$this->getString()` (which can be abstract as part of those traits) then we can achieve this with less effort. The question still is if its needed (can be a future issue though).

All fine, let's make our "smart tools" happy first =)

**Comment by cristianoc72** [comment]
I converted `$this->string` into `$this->getString()` and added some abstract methods into the traits.
Now the traits are (theoretically) "sharable". I also fixed collisions in PHP 7.2 and now this PR is ready to merge.

**Pull request merged**
