### PR TITLE
Resolves issue #25

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Resolves issue #25.
- Using the `composer cs-fix` script to fix the coding style.
- Using the `composer cs` script to check coding style without fix.
- To avoid unexpected error `Failed to write file "/home/travis/.php-cs-fixer/.php_cs.cache", "no reason  
   available".` message about failing to write `.php_cs.cache`.
Remove this writing cached file in `.php_cs` file.

### CODE REVIEW

**Comment by gossi** [comment]
I like the idea and for one reason I do not like (yet).

- I like it because as you said code being merged adheres to codestyle
- I do not like because once you have pushed your code, travis will _change_ that code before running test-suite.

I think I would rather fail the test-suite when cs-check is not ok. That way changing code is a manual step (although it is running a tool).

I'm open for more comments on this.

**Comment by peter279k** [comment]
> I like the idea and for one reason I do not like (yet).
> 
> * I like it because as you said code being merged adheres to codestyle
> * I do not like because once you have pushed your code, travis will _change_ that code before running test-suite.
> 
> I think I would rather fail the test-suite when cs-check is not ok. That way changing code is a manual step (although it is running a tool).
> 
> I'm open for more comments on this.

Hi @gossi, thanks for your reply.

I also use the `composer cs-fix` script to fix coding style manually.
And I use the `composer cs` script to check coding style without fix during Travis CI build.
To know more details about changes, you can look at the [.travis.yml](https://github.com/phootwork/phootwork/blob/6f3b1039d99bfe0eb7a809f6ab2e52ba6fdb74ea/.travis.yml) setting.

When the Travis CI build is failed, we can know that the coding style or failed unit tests.

I think it's fine because we can ensure that every oncoming PR should have correct coding style rather than we fix coding style after specific PR is merged.

**Comment by gossi** [comment]
Ah, so I missunderstand you 🙉. Your idea is to add code style check to travis WITHOUT autofixing? If so, yes I'm absolutely with that idea.

I would then wait for phootwork/php-cs-fixer-config#1 to land and then proceed with this one.

**Comment by peter279k** [comment]
Hi, yes. That's right :).

**Comment by gossi** [comment]
The PR in question was merged and I released a new version for cs-config-fixer. So you are unblocked :)

**Comment by peter279k** [comment]
Hi @gossi, thanks for your reply. I realize that why it has conflicts.

Perhaps I can close this PR and create PR again after the `php-cs-config`has released new version.

What do you think about this?

**Comment by cristianoc72** [comment]
My two cents (I hope to be useful):

Elegant solution:
1. `composer update`
2. re-run `composer cs-fix`
3. rebase your commit (during the rebase you'll fix the conflicts)

Easiest (and clearest) solution (split this PR into 2 parts):
1. close this PR
2. submit a new PR solving ONLY #25. Don't run `composer cs-fix`.
3. submit a second PR solving ONLY code standard (run cs-fix).

**Comment by peter279k** [comment]
Hi @cristianoc72, thanks for your reply.

I will try to use the first suggestion.

**Comment by peter279k** [comment]
I leave first suggestion because it's not easy and clear.
I use second PR because it's clear and easy.

**Pull request closed without merging**
