### PR TITLE
PHP 8.4 compatibility

### LINKED ISSUE #96: Php 8.4 compatibility
Merge into the monorepo https://github.com/phootwork/lang/pull/6 and add PHP 8.4 to Github Actions test workflow.

### PR DESCRIPTION
**Pull request by andypost**
Fixes #96 and supersedes https://github.com/phootwork/lang/pull/6

### CODE REVIEW

**Comment by gossi** [comment]
looks like a good bugfix to me, that likely silence warnings or errors under 8.4 - @cristianoc72 does that work with your 4.0 plans?

**Comment by cristianoc72** [comment]
Sure! It can be merged right now. We could also release 3.2.3 version, if @andypost needs this bugfix soon.

**Comment by andypost** [comment]
Would be great to get it in as it blocking a long chain of dependencies for next Drupal release and Drush

**Comment by cristianoc72** [comment]
The code is merged and it's ok but there's a problem in splitting monorepo and update the libraries. Probably it's about the new Github authentication token. I'll investigate it this evening.

**Comment by cristianoc72** [comment]
Done. Release 3.2.3 is out.
Thanks @andypost !

**Comment by andypost** [comment]
Thank you a lot! it was very helpful

**Pull request merged**
