### PR TITLE
Fix indentation

### PR DESCRIPTION
**Pull request by cristianoc72**
See https://github.com/phootwork/php-cs-fixer-config/pull/3

### CODE REVIEW

**Review by gossi — APPROVED** [review]

**Comment by peter279k** [comment]
I've the question about this.

Does the indentation coding style follow two spaces or tab?

**Comment by peter279k** [comment]
It looks like we follow the indentation style with tabs.

**Comment by gossi** [comment]
tabs

**Review by peter279k — APPROVED** [review]
Ok. It looks good to me.

**Pull request merged**
