### PR TITLE
Add codeclimate

### PR DESCRIPTION
**Pull request by cristianoc72**
Add [CodeClimate](https://codeclimate.com/github/phootwork/phootwork) quality tool.
See https://github.com/phootwork/phootwork/issues/4

### CODE REVIEW

**Review by gossi — APPROVED** [review]

**Comment by gossi** [comment]
nice, thanks for the addition :)

**Comment by gossi** [comment]
Is test-coverage supported? Or will it be done with this PR?

**Comment by gossi** [comment]
Aaaand can you add me on CC?

**Review by peter279k — APPROVED** [review]

**Comment by cristianoc72** [comment]
> Is test-coverage supported? Or will it be done with this PR?

With this PR. If you get a look at `.travis.yml` you can see the addictions needed to send the code coverage report to code climate, too.

**Pull request merged**
