### PR TITLE
Remove duplications

### PR DESCRIPTION
**Pull request by cristianoc72**
Refactor the code to remove a lot of duplications between `phootwork\lang\ArrayObject` and `phootwork\collection`.

**Details**

- Extract `phootwork\lang\AbstractArray` superclass containing methods shared between `phootwork\lang\ArrayObject` and `phootwork\collection\AbstractCollection`
- Introduce `phootwork\lang\parts\array_parts` containing some traits that share methods between `ArrayObject` and the various collections into `phootwork\collection` namespace.
- Rename `EnglishPluralizer` to `Inflector` since this classis not only a pluralizer but also a singularizer.

### CODE REVIEW

**Review by gossi — CHANGES_REQUESTED** [review]
All good, I like the change to rest parameters where applicable.

Only thing to change:

- `parts/array_parts/` -> `parts/array`
- `parts/text_parts/` -> `parts/text`

since this is just redundant (and underscore is only a naming convention for constants).

**Comment by cristianoc72** [comment]
> Only thing to change:
> 
>     * `parts/array_parts/` -> `parts/array`
> 
>     * `parts/text_parts/` -> `parts/text`

Yes, it was my first choice but it doesn't work, because array is a reserved key and using it in a namespace rises an error.
Perhaps a better choice is `parts\arr` ? Or even better put everything under `parts` without dividing `text` from `array`?

**Comment by gossi** [comment]
oh 😂 - that's impossible then 🙈 Going for `parts/` only is fine then :)

**Comment by cristianoc72** [comment]
Done.

**Review by gossi — APPROVED** [review]
I love these parts 😍 Go merge, very well done.

**Pull request merged**
